# Generated by Django 5.1.6 on 2025-02-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0003_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='additional_info',
            field=models.CharField(max_length=5000),
        ),
    ]
