# Generated by Django 5.1.6 on 2025-02-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0004_menuitem_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='additional_info',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
