# Generated by Django 4.2.7 on 2025-03-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0006_alter_menuitem_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
