# Generated by Django 5.2 on 2025-04-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0007_alter_menuitem_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='theveganmenu.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='theveganmenu.menusection'),
            preserve_default=False,
        ),
    ]
