# Generated by Django 5.2 on 2025-05-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0008_remove_menuitem_item_type_remove_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='menusection',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='theveganmenu.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menusection',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='theveganmenu.menu'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chain', to='theveganmenu.restaurantchain'),
        ),
    ]
