# Generated by Django 5.2 on 2025-05-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0009_restaurantchain_remove_menusection_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantchain',
            name='menu_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
