# Generated by Django 5.2 on 2025-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0010_restaurantchain_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
