# Generated by Django 5.2 on 2025-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0011_menusection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
