# Generated by Django 5.2 on 2025-05-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0012_menu_name_alter_menusection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
