# Generated by Django 5.2 on 2025-05-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0013_remove_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantchain',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='restaurantchain',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_menu', to='theveganmenu.menu'),
        ),
    ]
