# Generated by Django 5.2 on 2025-05-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0015_remove_menu_restaurant_menu_name_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='theveganmenu.menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='theveganmenu.menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chain', to='theveganmenu.restaurantchain'),
        ),
        migrations.AlterField(
            model_name='restaurantchain',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_menu', to='theveganmenu.menu'),
        ),
    ]
