# Generated by Django 5.2 on 2025-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0016_alter_menusection_menu_alter_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_fully_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
