# Generated by Django 5.2 on 2025-06-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0017_restaurant_is_fully_vegan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='link',
            new_name='website_link',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='map_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
