# Generated by Django 5.2.6 on 2025-09-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theveganmenu', '0018_rename_link_restaurant_website_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
